import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./Providers";
import SideBar from "@/components/SideBar/SideBar";
import NavBar from "@/components/NavBar/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "KinoHub Dashboard",
  description: "KinoHub Dashboard generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="flex">
            <div className="bg-[#ccc] dark:bg-[#272727] p-5 min-h-screen">
              <SideBar />
            </div>
            <div className="grow p-5">
              <NavBar />
              {children}
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
